/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.style.book.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.style.book.model.StyleBookTokenSet;
import com.liferay.style.book.service.StyleBookTokenSetLocalService;
import com.liferay.style.book.service.persistence.StyleBookTokenSetPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the style book token set local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.style.book.service.impl.StyleBookTokenSetLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.style.book.service.impl.StyleBookTokenSetLocalServiceImpl
 * @generated
 */
public abstract class StyleBookTokenSetLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   StyleBookTokenSetLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>StyleBookTokenSetLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.style.book.service.StyleBookTokenSetLocalServiceUtil</code>.
	 */

	/**
	 * Adds the style book token set to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StyleBookTokenSetLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param styleBookTokenSet the style book token set
	 * @return the style book token set that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public StyleBookTokenSet addStyleBookTokenSet(
		StyleBookTokenSet styleBookTokenSet) {

		styleBookTokenSet.setNew(true);

		return styleBookTokenSetPersistence.update(styleBookTokenSet);
	}

	/**
	 * Creates a new style book token set with the primary key. Does not add the style book token set to the database.
	 *
	 * @param styleBookTokenSetId the primary key for the new style book token set
	 * @return the new style book token set
	 */
	@Override
	@Transactional(enabled = false)
	public StyleBookTokenSet createStyleBookTokenSet(long styleBookTokenSetId) {
		return styleBookTokenSetPersistence.create(styleBookTokenSetId);
	}

	/**
	 * Deletes the style book token set with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StyleBookTokenSetLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param styleBookTokenSetId the primary key of the style book token set
	 * @return the style book token set that was removed
	 * @throws PortalException if a style book token set with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public StyleBookTokenSet deleteStyleBookTokenSet(long styleBookTokenSetId)
		throws PortalException {

		return styleBookTokenSetPersistence.remove(styleBookTokenSetId);
	}

	/**
	 * Deletes the style book token set from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StyleBookTokenSetLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param styleBookTokenSet the style book token set
	 * @return the style book token set that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public StyleBookTokenSet deleteStyleBookTokenSet(
		StyleBookTokenSet styleBookTokenSet) {

		return styleBookTokenSetPersistence.remove(styleBookTokenSet);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return styleBookTokenSetPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			StyleBookTokenSet.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return styleBookTokenSetPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.style.book.model.impl.StyleBookTokenSetModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return styleBookTokenSetPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.style.book.model.impl.StyleBookTokenSetModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return styleBookTokenSetPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return styleBookTokenSetPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return styleBookTokenSetPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public StyleBookTokenSet fetchStyleBookTokenSet(long styleBookTokenSetId) {
		return styleBookTokenSetPersistence.fetchByPrimaryKey(
			styleBookTokenSetId);
	}

	/**
	 * Returns the style book token set matching the UUID and group.
	 *
	 * @param uuid the style book token set's UUID
	 * @param groupId the primary key of the group
	 * @return the matching style book token set, or <code>null</code> if a matching style book token set could not be found
	 */
	@Override
	public StyleBookTokenSet fetchStyleBookTokenSetByUuidAndGroupId(
		String uuid, long groupId) {

		return styleBookTokenSetPersistence.fetchByUUID_G(uuid, groupId);
	}

	@Override
	public StyleBookTokenSet fetchStyleBookTokenSetByExternalReferenceCode(
		String externalReferenceCode, long groupId) {

		return styleBookTokenSetPersistence.fetchByERC_G(
			externalReferenceCode, groupId);
	}

	@Override
	public StyleBookTokenSet getStyleBookTokenSetByExternalReferenceCode(
			String externalReferenceCode, long groupId)
		throws PortalException {

		return styleBookTokenSetPersistence.findByERC_G(
			externalReferenceCode, groupId);
	}

	/**
	 * Returns the style book token set with the primary key.
	 *
	 * @param styleBookTokenSetId the primary key of the style book token set
	 * @return the style book token set
	 * @throws PortalException if a style book token set with the primary key could not be found
	 */
	@Override
	public StyleBookTokenSet getStyleBookTokenSet(long styleBookTokenSetId)
		throws PortalException {

		return styleBookTokenSetPersistence.findByPrimaryKey(
			styleBookTokenSetId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			styleBookTokenSetLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(StyleBookTokenSet.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("styleBookTokenSetId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			styleBookTokenSetLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(StyleBookTokenSet.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"styleBookTokenSetId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			styleBookTokenSetLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(StyleBookTokenSet.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("styleBookTokenSetId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<StyleBookTokenSet>() {

				@Override
				public void performAction(StyleBookTokenSet styleBookTokenSet)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, styleBookTokenSet);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(StyleBookTokenSet.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return styleBookTokenSetPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement StyleBookTokenSetLocalServiceImpl#deleteStyleBookTokenSet(StyleBookTokenSet) to avoid orphaned data");
		}

		return styleBookTokenSetLocalService.deleteStyleBookTokenSet(
			(StyleBookTokenSet)persistedModel);
	}

	@Override
	public BasePersistence<StyleBookTokenSet> getBasePersistence() {
		return styleBookTokenSetPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return styleBookTokenSetPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the style book token sets matching the UUID and company.
	 *
	 * @param uuid the UUID of the style book token sets
	 * @param companyId the primary key of the company
	 * @return the matching style book token sets, or an empty list if no matches were found
	 */
	@Override
	public List<StyleBookTokenSet> getStyleBookTokenSetsByUuidAndCompanyId(
		String uuid, long companyId) {

		return styleBookTokenSetPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of style book token sets matching the UUID and company.
	 *
	 * @param uuid the UUID of the style book token sets
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of style book token sets
	 * @param end the upper bound of the range of style book token sets (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching style book token sets, or an empty list if no matches were found
	 */
	@Override
	public List<StyleBookTokenSet> getStyleBookTokenSetsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<StyleBookTokenSet> orderByComparator) {

		return styleBookTokenSetPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the style book token set matching the UUID and group.
	 *
	 * @param uuid the style book token set's UUID
	 * @param groupId the primary key of the group
	 * @return the matching style book token set
	 * @throws PortalException if a matching style book token set could not be found
	 */
	@Override
	public StyleBookTokenSet getStyleBookTokenSetByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return styleBookTokenSetPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the style book token sets.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.style.book.model.impl.StyleBookTokenSetModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of style book token sets
	 * @param end the upper bound of the range of style book token sets (not inclusive)
	 * @return the range of style book token sets
	 */
	@Override
	public List<StyleBookTokenSet> getStyleBookTokenSets(int start, int end) {
		return styleBookTokenSetPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of style book token sets.
	 *
	 * @return the number of style book token sets
	 */
	@Override
	public int getStyleBookTokenSetsCount() {
		return styleBookTokenSetPersistence.countAll();
	}

	/**
	 * Updates the style book token set in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StyleBookTokenSetLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param styleBookTokenSet the style book token set
	 * @return the style book token set that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public StyleBookTokenSet updateStyleBookTokenSet(
		StyleBookTokenSet styleBookTokenSet) {

		return styleBookTokenSetPersistence.update(styleBookTokenSet);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			StyleBookTokenSetLocalService.class, IdentifiableOSGiService.class,
			CTService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		styleBookTokenSetLocalService = (StyleBookTokenSetLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return StyleBookTokenSetLocalService.class.getName();
	}

	@Override
	public CTPersistence<StyleBookTokenSet> getCTPersistence() {
		return styleBookTokenSetPersistence;
	}

	@Override
	public Class<StyleBookTokenSet> getModelClass() {
		return StyleBookTokenSet.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<StyleBookTokenSet>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(styleBookTokenSetPersistence);
	}

	protected String getModelClassName() {
		return StyleBookTokenSet.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = styleBookTokenSetPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected StyleBookTokenSetLocalService styleBookTokenSetLocalService;

	@Reference
	protected StyleBookTokenSetPersistence styleBookTokenSetPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		StyleBookTokenSetLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:1101969773