dependencies {
	testIntegrationImplementation project(":apps:feature-flag:feature-flag-web")
	testIntegrationImplementation project(":apps:portal:portal-upgrade-test-util")
	testIntegrationImplementation project(":apps:static:portal:portal-upgrade-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}