/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.style.book.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StyleBookTokenCategory service. Represents a row in the &quot;StyleBookTokenCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.style.book.model.impl.StyleBookTokenCategoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.style.book.model.impl.StyleBookTokenCategoryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StyleBookTokenCategory
 * @generated
 */
@ProviderType
public interface StyleBookTokenCategoryModel
	extends BaseModel<StyleBookTokenCategory>, CTModel<StyleBookTokenCategory>,
			GroupedModel, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a style book token category model instance should use the {@link StyleBookTokenCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this style book token category.
	 *
	 * @return the primary key of this style book token category
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this style book token category.
	 *
	 * @param primaryKey the primary key of this style book token category
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this style book token category.
	 *
	 * @return the mvcc version of this style book token category
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this style book token category.
	 *
	 * @param mvccVersion the mvcc version of this style book token category
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this style book token category.
	 *
	 * @return the ct collection ID of this style book token category
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this style book token category.
	 *
	 * @param ctCollectionId the ct collection ID of this style book token category
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the style book token category ID of this style book token category.
	 *
	 * @return the style book token category ID of this style book token category
	 */
	public long getStyleBookTokenCategoryId();

	/**
	 * Sets the style book token category ID of this style book token category.
	 *
	 * @param styleBookTokenCategoryId the style book token category ID of this style book token category
	 */
	public void setStyleBookTokenCategoryId(long styleBookTokenCategoryId);

	/**
	 * Returns the group ID of this style book token category.
	 *
	 * @return the group ID of this style book token category
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this style book token category.
	 *
	 * @param groupId the group ID of this style book token category
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this style book token category.
	 *
	 * @return the company ID of this style book token category
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this style book token category.
	 *
	 * @param companyId the company ID of this style book token category
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this style book token category.
	 *
	 * @return the user ID of this style book token category
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this style book token category.
	 *
	 * @param userId the user ID of this style book token category
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this style book token category.
	 *
	 * @return the user uuid of this style book token category
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this style book token category.
	 *
	 * @param userUuid the user uuid of this style book token category
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this style book token category.
	 *
	 * @return the user name of this style book token category
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this style book token category.
	 *
	 * @param userName the user name of this style book token category
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this style book token category.
	 *
	 * @return the create date of this style book token category
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this style book token category.
	 *
	 * @param createDate the create date of this style book token category
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this style book token category.
	 *
	 * @return the modified date of this style book token category
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this style book token category.
	 *
	 * @param modifiedDate the modified date of this style book token category
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the style book entry ID of this style book token category.
	 *
	 * @return the style book entry ID of this style book token category
	 */
	public long getStyleBookEntryId();

	/**
	 * Sets the style book entry ID of this style book token category.
	 *
	 * @param styleBookEntryId the style book entry ID of this style book token category
	 */
	public void setStyleBookEntryId(long styleBookEntryId);

	/**
	 * Returns the theme frontend token definition ID of this style book token category.
	 *
	 * @return the theme frontend token definition ID of this style book token category
	 */
	@AutoEscape
	public String getThemeFrontendTokenDefinitionId();

	/**
	 * Sets the theme frontend token definition ID of this style book token category.
	 *
	 * @param themeFrontendTokenDefinitionId the theme frontend token definition ID of this style book token category
	 */
	public void setThemeFrontendTokenDefinitionId(
		String themeFrontendTokenDefinitionId);

	/**
	 * Returns the name of this style book token category.
	 *
	 * @return the name of this style book token category
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this style book token category.
	 *
	 * @param name the name of this style book token category
	 */
	public void setName(String name);

	/**
	 * Returns the description of this style book token category.
	 *
	 * @return the description of this style book token category
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this style book token category.
	 *
	 * @param description the description of this style book token category
	 */
	public void setDescription(String description);

	@Override
	public StyleBookTokenCategory cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-2115427731