/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.style.book.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ExternalReferenceCodeModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StyleBookTokenSet service. Represents a row in the &quot;StyleBookTokenSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.style.book.model.impl.StyleBookTokenSetModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.style.book.model.impl.StyleBookTokenSetImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StyleBookTokenSet
 * @generated
 */
@ProviderType
public interface StyleBookTokenSetModel
	extends BaseModel<StyleBookTokenSet>, CTModel<StyleBookTokenSet>,
			ExternalReferenceCodeModel, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a style book token set model instance should use the {@link StyleBookTokenSet} interface instead.
	 */

	/**
	 * Returns the primary key of this style book token set.
	 *
	 * @return the primary key of this style book token set
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this style book token set.
	 *
	 * @param primaryKey the primary key of this style book token set
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this style book token set.
	 *
	 * @return the mvcc version of this style book token set
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this style book token set.
	 *
	 * @param mvccVersion the mvcc version of this style book token set
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this style book token set.
	 *
	 * @return the ct collection ID of this style book token set
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this style book token set.
	 *
	 * @param ctCollectionId the ct collection ID of this style book token set
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the uuid of this style book token set.
	 *
	 * @return the uuid of this style book token set
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this style book token set.
	 *
	 * @param uuid the uuid of this style book token set
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this style book token set.
	 *
	 * @return the external reference code of this style book token set
	 */
	@AutoEscape
	@Override
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this style book token set.
	 *
	 * @param externalReferenceCode the external reference code of this style book token set
	 */
	@Override
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the style book token set ID of this style book token set.
	 *
	 * @return the style book token set ID of this style book token set
	 */
	public long getStyleBookTokenSetId();

	/**
	 * Sets the style book token set ID of this style book token set.
	 *
	 * @param styleBookTokenSetId the style book token set ID of this style book token set
	 */
	public void setStyleBookTokenSetId(long styleBookTokenSetId);

	/**
	 * Returns the group ID of this style book token set.
	 *
	 * @return the group ID of this style book token set
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this style book token set.
	 *
	 * @param groupId the group ID of this style book token set
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this style book token set.
	 *
	 * @return the company ID of this style book token set
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this style book token set.
	 *
	 * @param companyId the company ID of this style book token set
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this style book token set.
	 *
	 * @return the user ID of this style book token set
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this style book token set.
	 *
	 * @param userId the user ID of this style book token set
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this style book token set.
	 *
	 * @return the user uuid of this style book token set
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this style book token set.
	 *
	 * @param userUuid the user uuid of this style book token set
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this style book token set.
	 *
	 * @return the user name of this style book token set
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this style book token set.
	 *
	 * @param userName the user name of this style book token set
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this style book token set.
	 *
	 * @return the create date of this style book token set
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this style book token set.
	 *
	 * @param createDate the create date of this style book token set
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this style book token set.
	 *
	 * @return the modified date of this style book token set
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this style book token set.
	 *
	 * @param modifiedDate the modified date of this style book token set
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the style book entry ID of this style book token set.
	 *
	 * @return the style book entry ID of this style book token set
	 */
	public long getStyleBookEntryId();

	/**
	 * Sets the style book entry ID of this style book token set.
	 *
	 * @param styleBookEntryId the style book entry ID of this style book token set
	 */
	public void setStyleBookEntryId(long styleBookEntryId);

	/**
	 * Returns the description of this style book token set.
	 *
	 * @return the description of this style book token set
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this style book token set.
	 *
	 * @param description the description of this style book token set
	 */
	public void setDescription(String description);

	/**
	 * Returns the frontend token category name of this style book token set.
	 *
	 * @return the frontend token category name of this style book token set
	 */
	@AutoEscape
	public String getFrontendTokenCategoryName();

	/**
	 * Sets the frontend token category name of this style book token set.
	 *
	 * @param frontendTokenCategoryName the frontend token category name of this style book token set
	 */
	public void setFrontendTokenCategoryName(String frontendTokenCategoryName);

	/**
	 * Returns the name of this style book token set.
	 *
	 * @return the name of this style book token set
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this style book token set.
	 *
	 * @param name the name of this style book token set
	 */
	public void setName(String name);

	/**
	 * Returns the theme ID of this style book token set.
	 *
	 * @return the theme ID of this style book token set
	 */
	@AutoEscape
	public String getThemeId();

	/**
	 * Sets the theme ID of this style book token set.
	 *
	 * @param themeId the theme ID of this style book token set
	 */
	public void setThemeId(String themeId);

	@Override
	public StyleBookTokenSet cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1732582532