/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.style.book.model.impl;

import com.liferay.style.book.model.StyleBookTokenCategory;
import com.liferay.style.book.service.StyleBookTokenCategoryLocalServiceUtil;

/**
 * The extended model base implementation for the StyleBookTokenCategory service. Represents a row in the &quot;StyleBookTokenCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StyleBookTokenCategoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StyleBookTokenCategoryImpl
 * @see StyleBookTokenCategory
 * @generated
 */
public abstract class StyleBookTokenCategoryBaseImpl
	extends StyleBookTokenCategoryModelImpl implements StyleBookTokenCategory {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a style book token category model instance should use the <code>StyleBookTokenCategory</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			StyleBookTokenCategoryLocalServiceUtil.addStyleBookTokenCategory(
				this);
		}
		else {
			StyleBookTokenCategoryLocalServiceUtil.updateStyleBookTokenCategory(
				this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1412691462