/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.style.book.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.style.book.model.StyleBookTokenSet;
import com.liferay.style.book.model.StyleBookTokenSetModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the StyleBookTokenSet service. Represents a row in the &quot;StyleBookTokenSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>StyleBookTokenSetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StyleBookTokenSetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StyleBookTokenSetImpl
 * @generated
 */
@JSON(strict = true)
public class StyleBookTokenSetModelImpl
	extends BaseModelImpl<StyleBookTokenSet> implements StyleBookTokenSetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a style book token set model instance should use the <code>StyleBookTokenSet</code> interface instead.
	 */
	public static final String TABLE_NAME = "StyleBookTokenSet";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"styleBookTokenSetId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"styleBookEntryId", Types.BIGINT},
		{"description", Types.VARCHAR},
		{"frontendTokenCategoryName", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"themeId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("styleBookTokenSetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("styleBookEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("frontendTokenCategoryName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("themeId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table StyleBookTokenSet (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,styleBookTokenSetId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,styleBookEntryId LONG,description STRING null,frontendTokenCategoryName VARCHAR(75) null,name VARCHAR(75) null,themeId VARCHAR(75) null,primary key (styleBookTokenSetId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table StyleBookTokenSet";

	public static final String ENTITY_ALIAS = "styleBookTokenSet";

	public static final String ORDER_BY_JPQL =
		" ORDER BY styleBookTokenSet.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY StyleBookTokenSet.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FRONTENDTOKENCATEGORYNAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STYLEBOOKENTRYID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long THEMEID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public StyleBookTokenSetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _styleBookTokenSetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStyleBookTokenSetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _styleBookTokenSetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StyleBookTokenSet.class;
	}

	@Override
	public String getModelClassName() {
		return StyleBookTokenSet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<StyleBookTokenSet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<StyleBookTokenSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StyleBookTokenSet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((StyleBookTokenSet)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<StyleBookTokenSet, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<StyleBookTokenSet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(StyleBookTokenSet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<StyleBookTokenSet, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<StyleBookTokenSet, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<StyleBookTokenSet, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<StyleBookTokenSet, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<StyleBookTokenSet, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", StyleBookTokenSet::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", StyleBookTokenSet::getCtCollectionId);
			attributeGetterFunctions.put("uuid", StyleBookTokenSet::getUuid);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				StyleBookTokenSet::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"styleBookTokenSetId",
				StyleBookTokenSet::getStyleBookTokenSetId);
			attributeGetterFunctions.put(
				"groupId", StyleBookTokenSet::getGroupId);
			attributeGetterFunctions.put(
				"companyId", StyleBookTokenSet::getCompanyId);
			attributeGetterFunctions.put(
				"userId", StyleBookTokenSet::getUserId);
			attributeGetterFunctions.put(
				"userName", StyleBookTokenSet::getUserName);
			attributeGetterFunctions.put(
				"createDate", StyleBookTokenSet::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", StyleBookTokenSet::getModifiedDate);
			attributeGetterFunctions.put(
				"styleBookEntryId", StyleBookTokenSet::getStyleBookEntryId);
			attributeGetterFunctions.put(
				"description", StyleBookTokenSet::getDescription);
			attributeGetterFunctions.put(
				"frontendTokenCategoryName",
				StyleBookTokenSet::getFrontendTokenCategoryName);
			attributeGetterFunctions.put("name", StyleBookTokenSet::getName);
			attributeGetterFunctions.put(
				"themeId", StyleBookTokenSet::getThemeId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<StyleBookTokenSet, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<StyleBookTokenSet, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<StyleBookTokenSet, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<StyleBookTokenSet, Long>)
					StyleBookTokenSet::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<StyleBookTokenSet, Long>)
					StyleBookTokenSet::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<StyleBookTokenSet, String>)
					StyleBookTokenSet::setUuid);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<StyleBookTokenSet, String>)
					StyleBookTokenSet::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"styleBookTokenSetId",
				(BiConsumer<StyleBookTokenSet, Long>)
					StyleBookTokenSet::setStyleBookTokenSetId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<StyleBookTokenSet, Long>)
					StyleBookTokenSet::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<StyleBookTokenSet, Long>)
					StyleBookTokenSet::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<StyleBookTokenSet, Long>)
					StyleBookTokenSet::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<StyleBookTokenSet, String>)
					StyleBookTokenSet::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<StyleBookTokenSet, Date>)
					StyleBookTokenSet::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<StyleBookTokenSet, Date>)
					StyleBookTokenSet::setModifiedDate);
			attributeSetterBiConsumers.put(
				"styleBookEntryId",
				(BiConsumer<StyleBookTokenSet, Long>)
					StyleBookTokenSet::setStyleBookEntryId);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<StyleBookTokenSet, String>)
					StyleBookTokenSet::setDescription);
			attributeSetterBiConsumers.put(
				"frontendTokenCategoryName",
				(BiConsumer<StyleBookTokenSet, String>)
					StyleBookTokenSet::setFrontendTokenCategoryName);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<StyleBookTokenSet, String>)
					StyleBookTokenSet::setName);
			attributeSetterBiConsumers.put(
				"themeId",
				(BiConsumer<StyleBookTokenSet, String>)
					StyleBookTokenSet::setThemeId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getStyleBookTokenSetId() {
		return _styleBookTokenSetId;
	}

	@Override
	public void setStyleBookTokenSetId(long styleBookTokenSetId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_styleBookTokenSetId = styleBookTokenSetId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getStyleBookEntryId() {
		return _styleBookEntryId;
	}

	@Override
	public void setStyleBookEntryId(long styleBookEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_styleBookEntryId = styleBookEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalStyleBookEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("styleBookEntryId"));
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getFrontendTokenCategoryName() {
		if (_frontendTokenCategoryName == null) {
			return "";
		}
		else {
			return _frontendTokenCategoryName;
		}
	}

	@Override
	public void setFrontendTokenCategoryName(String frontendTokenCategoryName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_frontendTokenCategoryName = frontendTokenCategoryName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFrontendTokenCategoryName() {
		return getColumnOriginalValue("frontendTokenCategoryName");
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public String getThemeId() {
		if (_themeId == null) {
			return "";
		}
		else {
			return _themeId;
		}
	}

	@Override
	public void setThemeId(String themeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_themeId = themeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalThemeId() {
		return getColumnOriginalValue("themeId");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(StyleBookTokenSet.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), StyleBookTokenSet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StyleBookTokenSet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, StyleBookTokenSet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StyleBookTokenSetImpl styleBookTokenSetImpl =
			new StyleBookTokenSetImpl();

		styleBookTokenSetImpl.setMvccVersion(getMvccVersion());
		styleBookTokenSetImpl.setCtCollectionId(getCtCollectionId());
		styleBookTokenSetImpl.setUuid(getUuid());
		styleBookTokenSetImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		styleBookTokenSetImpl.setStyleBookTokenSetId(getStyleBookTokenSetId());
		styleBookTokenSetImpl.setGroupId(getGroupId());
		styleBookTokenSetImpl.setCompanyId(getCompanyId());
		styleBookTokenSetImpl.setUserId(getUserId());
		styleBookTokenSetImpl.setUserName(getUserName());
		styleBookTokenSetImpl.setCreateDate(getCreateDate());
		styleBookTokenSetImpl.setModifiedDate(getModifiedDate());
		styleBookTokenSetImpl.setStyleBookEntryId(getStyleBookEntryId());
		styleBookTokenSetImpl.setDescription(getDescription());
		styleBookTokenSetImpl.setFrontendTokenCategoryName(
			getFrontendTokenCategoryName());
		styleBookTokenSetImpl.setName(getName());
		styleBookTokenSetImpl.setThemeId(getThemeId());

		styleBookTokenSetImpl.resetOriginalValues();

		return styleBookTokenSetImpl;
	}

	@Override
	public StyleBookTokenSet cloneWithOriginalValues() {
		StyleBookTokenSetImpl styleBookTokenSetImpl =
			new StyleBookTokenSetImpl();

		styleBookTokenSetImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		styleBookTokenSetImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		styleBookTokenSetImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		styleBookTokenSetImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		styleBookTokenSetImpl.setStyleBookTokenSetId(
			this.<Long>getColumnOriginalValue("styleBookTokenSetId"));
		styleBookTokenSetImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		styleBookTokenSetImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		styleBookTokenSetImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		styleBookTokenSetImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		styleBookTokenSetImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		styleBookTokenSetImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		styleBookTokenSetImpl.setStyleBookEntryId(
			this.<Long>getColumnOriginalValue("styleBookEntryId"));
		styleBookTokenSetImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		styleBookTokenSetImpl.setFrontendTokenCategoryName(
			this.<String>getColumnOriginalValue("frontendTokenCategoryName"));
		styleBookTokenSetImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		styleBookTokenSetImpl.setThemeId(
			this.<String>getColumnOriginalValue("themeId"));

		return styleBookTokenSetImpl;
	}

	@Override
	public int compareTo(StyleBookTokenSet styleBookTokenSet) {
		int value = 0;

		value = getName().compareTo(styleBookTokenSet.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof StyleBookTokenSet)) {
			return false;
		}

		StyleBookTokenSet styleBookTokenSet = (StyleBookTokenSet)object;

		long primaryKey = styleBookTokenSet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<StyleBookTokenSet> toCacheModel() {
		StyleBookTokenSetCacheModel styleBookTokenSetCacheModel =
			new StyleBookTokenSetCacheModel();

		styleBookTokenSetCacheModel.mvccVersion = getMvccVersion();

		styleBookTokenSetCacheModel.ctCollectionId = getCtCollectionId();

		styleBookTokenSetCacheModel.uuid = getUuid();

		String uuid = styleBookTokenSetCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			styleBookTokenSetCacheModel.uuid = null;
		}

		styleBookTokenSetCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			styleBookTokenSetCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			styleBookTokenSetCacheModel.externalReferenceCode = null;
		}

		styleBookTokenSetCacheModel.styleBookTokenSetId =
			getStyleBookTokenSetId();

		styleBookTokenSetCacheModel.groupId = getGroupId();

		styleBookTokenSetCacheModel.companyId = getCompanyId();

		styleBookTokenSetCacheModel.userId = getUserId();

		styleBookTokenSetCacheModel.userName = getUserName();

		String userName = styleBookTokenSetCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			styleBookTokenSetCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			styleBookTokenSetCacheModel.createDate = createDate.getTime();
		}
		else {
			styleBookTokenSetCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			styleBookTokenSetCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			styleBookTokenSetCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		styleBookTokenSetCacheModel.styleBookEntryId = getStyleBookEntryId();

		styleBookTokenSetCacheModel.description = getDescription();

		String description = styleBookTokenSetCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			styleBookTokenSetCacheModel.description = null;
		}

		styleBookTokenSetCacheModel.frontendTokenCategoryName =
			getFrontendTokenCategoryName();

		String frontendTokenCategoryName =
			styleBookTokenSetCacheModel.frontendTokenCategoryName;

		if ((frontendTokenCategoryName != null) &&
			(frontendTokenCategoryName.length() == 0)) {

			styleBookTokenSetCacheModel.frontendTokenCategoryName = null;
		}

		styleBookTokenSetCacheModel.name = getName();

		String name = styleBookTokenSetCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			styleBookTokenSetCacheModel.name = null;
		}

		styleBookTokenSetCacheModel.themeId = getThemeId();

		String themeId = styleBookTokenSetCacheModel.themeId;

		if ((themeId != null) && (themeId.length() == 0)) {
			styleBookTokenSetCacheModel.themeId = null;
		}

		return styleBookTokenSetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<StyleBookTokenSet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<StyleBookTokenSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StyleBookTokenSet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(StyleBookTokenSet)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, StyleBookTokenSet>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					StyleBookTokenSet.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private String _externalReferenceCode;
	private long _styleBookTokenSetId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _styleBookEntryId;
	private String _description;
	private String _frontendTokenCategoryName;
	private String _name;
	private String _themeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<StyleBookTokenSet, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((StyleBookTokenSet)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("styleBookTokenSetId", _styleBookTokenSetId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("styleBookEntryId", _styleBookEntryId);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put(
			"frontendTokenCategoryName", _frontendTokenCategoryName);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("themeId", _themeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("externalReferenceCode", 8L);

		columnBitmasks.put("styleBookTokenSetId", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		columnBitmasks.put("styleBookEntryId", 2048L);

		columnBitmasks.put("description", 4096L);

		columnBitmasks.put("frontendTokenCategoryName", 8192L);

		columnBitmasks.put("name", 16384L);

		columnBitmasks.put("themeId", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private StyleBookTokenSet _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1779752862